LEGAL_REFERENCES = {
 "going_concern":{"summary":"The auditor has raised a material uncertainty about the company's ability to continue as a going concern.","laws":["Companies Act, 2013 – Section 134(5)(d): Directors must confirm the company is a going concern.","ICAI SA 570 (Going Concern): Auditor's responsibility to evaluate management's use of going concern basis.","SEBI LODR – Regulation 17: Audit committee must review the going concern assumption.","RBI Guidelines on Early Warning Signals: Going concern issues are a critical red flag for lenders."],"action":"Immediate review of financial projections, liquidity position, and debt repayment capacity. Consider special audit of cash flows and working capital."},
 "related_party":{"summary":"Significant related-party transactions have been identified that may indicate conflict of interest, fund diversion, or siphoning.","laws":["Companies Act, 2013 – Section 188: Related-party transactions require board approval and disclosure.","Companies Act, 2013 – Section 184: Directors must disclose their interest in any contract or arrangement.","SEBI LODR – Regulation 23: Material RPTs must be disclosed to stock exchanges.","ICAI Ind AS 24: Related-party disclosures are mandatory in financial statements."],"action":"Review all related-party transactions for arm's length pricing, board approval, and proper disclosure. Consider independent valuation of significant transactions."},
 "pending_litigation":{"summary":"Pending litigation, disputes, or arbitration proceedings have been identified.","laws":["Companies Act, 2013 – Schedule III: Contingent liabilities including pending litigation must be disclosed.","Arbitration and Conciliation Act, 1996: Governs arbitration proceedings and enforcement of awards.","Code of Civil Procedure, 1908: Governs civil litigation before Indian courts.","ICAI AS 29: Provisions, Contingent Liabilities, and Contingent Assets."],"action":"Obtain status and quantum estimate for each proceeding from legal counsel; assess provisioning adequacy and disclosure completeness."},
 "contingent_liability":{"summary":"Significant contingent liabilities have been identified, which could materially impact the company's financial position.","laws":["Companies Act, 2013 – Schedule III: Contingent liabilities must be disclosed in the financial statements.","ICAI AS 29: Provisions, Contingent Liabilities, and Contingent Assets.","RBI Guidelines on Provisioning: Contingent liabilities require provisioning as per RBI norms."],"action":"Assess the likelihood and potential quantum of each contingent liability. Ensure adequate provisioning and disclosure."},
 "audit_qualification":{"summary":"The auditor has issued a qualified opinion or emphasized a specific matter in their report.","laws":["Companies Act, 2013 – Section 143: Auditor's duties and reporting responsibilities.","ICAI SA 705: Modifications to the opinion in the independent auditor's report.","ICAI SA 706: Emphasis of Matter paragraphs.","SEBI LODR – Regulation 33: Audit report must be submitted with financial results."],"action":"Address the auditor's concerns, implement corrective actions, and ensure future audit opinions are unqualified."},
 "default":{"summary":"Indicators of potential defaults or non-payment of obligations have been identified.","laws":["RBI Guidelines on Early Warning Signals: Default indicators are critical for lenders.","SEBI LODR – Regulation 30: Defaults on debt obligations must be disclosed.","Insolvency and Bankruptcy Code, 2016 – Section 7: Default may trigger insolvency proceedings."],"action":"Review debt repayment schedule, cash flow projections, and covenant compliance. Consider refinancing or restructuring if necessary."},
 "regulatory":{"summary":"Regulatory or enforcement action (e.g., CBI, ED, SEBI, RBI) has been mentioned in the report.","laws":["Companies Act, 2013 – Section 134(3)(a): Board's report must disclose details of proceedings under any law.","SEBI LODR – Regulation 30: Material regulatory actions must be disclosed.","RBI Master Circular on Frauds: Regulatory actions must be reported."],"action":"Engage with regulators, ensure compliance, and implement corrective actions to prevent recurrence."},
 "npa":{"summary":"Non-performing assets (NPA) or bad loans have been identified in the company's portfolio.","laws":["RBI Guidelines on Asset Classification: NPAs must be classified and provisioned.","Insolvency and Bankruptcy Code, 2016 – Section 7: NPAs may trigger insolvency proceedings."],"action":"Review loan portfolio, provisioning adequacy, and recovery mechanisms. Consider restructuring or write-offs where appropriate."},
 "shell_company":{"summary":"Potential shell company or benami entity indicators have been identified.","laws":["Prevention of Benami Transactions Act, 1988: Benami transactions are prohibited.","Prevention of Money Laundering Act, 2002 (PMLA): Shell companies may be used for money laundering.","Income Tax Act, 1961 – Section 68: Cash credits must be explained."],"action":"Investigate the entities identified, verify their legitimate business purpose, and consider filing appropriate disclosures."},
 "demand_notice":{"summary":"A demand notice or show cause notice has been received from a regulatory authority.","laws":["Income Tax Act, 1961 – Section 156: Notice of demand.","Goods and Services Tax Act, 2017: Show cause notices and demand orders."],"action":"Respond to the notice promptly, engage legal counsel, and seek resolution through appropriate channels."},
 "termination":{"summary":"Termination risk has been identified, indicating potential loss of a critical contract, license, or arrangement.","laws":["Indian Contract Act, 1872 – Section 73: Compensation for breach of contract.","Specific Relief Act, 1963: Remedies for breach of contract."],"action":"Review the contract/license terms, assess the risk of termination, and consider legal remedies."},
 "guarantee":{"summary":"Guarantee or indemnity exposure has been identified, indicating potential contingent liability.","laws":["Companies Act, 2013 – Section 186: Guarantees require board approval.","RBI Guidelines on Corporate Guarantees: Guarantees must be properly valued and disclosed."],"action":"Assess the risk of each guarantee, ensure adequate provisioning, and consider reducing exposure."},
 "promoter":{"summary":"Promoter or controlling shareholder involvement has been identified.","laws":["Companies Act, 2013 – Section 184: Directors must disclose their interest.","SEBI LODR – Regulation 26: Promoter shareholding must be disclosed."],"action":"Review promoter-related transactions, ensure compliance with disclosure requirements, and implement robust corporate governance practices."},
 "iepf":{"summary":"IEPF or unclaimed dividend transfer has been identified.","laws":["Companies Act, 2013 – Section 124: Unclaimed dividends must be transferred to IEPF.","Companies Act, 2013 – Section 125: Investor Education and Protection Fund."],"action":"Ensure timely transfer of unclaimed dividends and share certificates to IEPF."}
}
